development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: oreckr_test
  pool: 5
  username: oreckr_test
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: oreckr_production
  pool: 5
  username: oreckr_production
  password:
